apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    targetRevision: HEAD
    path: application
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
